[package]
name = "rbx-lass"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "Compiles sass-like code to roblox stylesheet lua"
repository = "https://github.com/toodols/lass"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
glob = "0.3.3"
nom = "8.0.0"
